codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        # Allow coverage to drop by 1% for PRs
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "setup.py" 