# This workflow will upload a Python Package when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_run:
    workflows: ["Bump Version"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  id-token: write  # Required for PyPI trusted publishing

jobs:
  check_version_bump:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          # If triggered by workflow_run, make sure to get the right commit
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
          fetch-depth: 0
      
      - name: Debug git info
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Commit message: $(git log -1 --pretty=%B)"
          echo "Files changed:"
          git show --name-status HEAD
      
      - name: Extract version
        id: get_version
        run: |
          # First check pyproject.toml content to ensure we're seeing the most recent version
          echo "pyproject.toml content:"
          cat pyproject.toml | grep -A 2 "version ="
          
          # Get version directly from file
          VERSION=$(grep -m 1 "version = " pyproject.toml | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          
          # Double check from git tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest git tag: $LATEST_TAG"
          
          echo "Extracted version from pyproject.toml: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  deploy:
    needs: check_version_bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check_version_bump.outputs.version }}
          name: Release v${{ needs.check_version_bump.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }} 